SELECT TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME,SUM(AMOUNT) 재고
FROM(SELECT TEAM_CODE ,PRODUCT_CODE ,PRODUCT_TB.PRODUCT_NAME PRODUCT_NAME,
(CASE 
	WHEN IN_OUT_SALES_ST = 'IN'
	THEN TO_NUMBER(TO_CHAR(AMOUNT))   
	WHEN IN_OUT_SALES_ST = 'OUT'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
	WHEN IN_OUT_SALES_ST = 'SALES'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
END) AMOUNT 
FROM STOCK_TB
FULL JOIN PRODUCT_TB USING(PRODUCT_CODE))
GROUP BY TEAM_CODE ,PRODUCT_CODE ,PRODUCT_NAME
HAVING TEAM_CODE = 'DC'
ORDER BY 1,2;

SELECT TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME,SUM(AMOUNT) 재고
FROM(SELECT TEAM_CODE ,PRODUCT_CODE ,PRODUCT_TB.PRODUCT_NAME PRODUCT_NAME,
(CASE 
	WHEN IN_OUT_SALES_ST = 'IN'
	THEN TO_NUMBER(TO_CHAR(AMOUNT))   
	WHEN IN_OUT_SALES_ST = 'OUT'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
	WHEN IN_OUT_SALES_ST = 'SALES'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
END) AMOUNT 
FROM STOCK_TB
FULL JOIN PRODUCT_TB USING(PRODUCT_CODE))
GROUP BY TEAM_CODE ,PRODUCT_CODE ,PRODUCT_NAME
HAVING TEAM_CODE = 'DM001'
ORDER BY 1,2;
INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,'OUT',2,TO_DATE('2022-07-20','YYYY-MM-DD'),'Y','SC00003','DM001','DM002');

INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,'SALES',5,TO_DATE('2022-07-20','YYYY-MM-DD'),'Y','HC00001','DM002',NULL);

INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,'IN',10,TO_DATE('2022-07-02','YYYY-MM-DD'),'Y','SC00001','DM002','DC');
INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,'OUT',10,TO_DATE('2022-07-02','YYYY-MM-DD'),'Y','SC00001','DC','DM002');

INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,NULL,0,TO_DATE('2022-07-01','YYYY-MM-DD'),'Y','SC00003','DM002',NULL);
INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,NULL,0,TO_DATE('2022-07-01','YYYY-MM-DD'),'Y','BC00001','DM002',NULL);
INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,NULL,0,TO_DATE('2022-07-01','YYYY-MM-DD'),'Y','BC00002','DM002',NULL);
INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,NULL,0,TO_DATE('2022-07-01','YYYY-MM-DD'),'Y','BC00003','DM002',NULL);
INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,NULL,0,TO_DATE('2022-07-01','YYYY-MM-DD'),'Y','HC00001','DM002',NULL);
INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,NULL,0,TO_DATE('2022-07-01','YYYY-MM-DD'),'Y','HC00002','DM002',NULL);
INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,NULL,0,TO_DATE('2022-07-01','YYYY-MM-DD'),'Y','HC00003','DM002',NULL);
INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,NULL,0,TO_DATE('2022-07-01','YYYY-MM-DD'),'Y','MU00001','DM002',NULL);
INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,NULL,0,TO_DATE('2022-07-01','YYYY-MM-DD'),'Y','MU00002','DM002',NULL);
INSERT INTO STOCK_TB VALUES(SEQ_STOCK_NO.NEXTVAL,NULL,0,TO_DATE('2022-07-01','YYYY-MM-DD'),'Y','MU00003','DM002',NULL);

------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------
SELECT TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME, SUM(AMOUNT)
FROM STOCK_TB
FULL JOIN PRODUCT_TB USING(PRODUCT_CODE)
WHERE IN_OUT_SALES_ST = 'SALES'
GROUP BY TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME;
-------------------------------------------------------------------------
SELECT main.TEAM_CODE ,main.PRODUCT_CODE,sub.PRODUCT_CODE,main.PRODUCT_NAME , main.수량 재고수량, sub.수량 판매수량
FROM (SELECT TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME,SUM(AMOUNT) 수량
FROM(SELECT TEAM_CODE ,PRODUCT_CODE ,PRODUCT_TB.PRODUCT_NAME PRODUCT_NAME,
(CASE 
	WHEN IN_OUT_SALES_ST = 'IN'
	THEN TO_NUMBER(TO_CHAR(AMOUNT))   
	WHEN IN_OUT_SALES_ST = 'OUT'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
	WHEN IN_OUT_SALES_ST = 'SALES'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
END) AMOUNT 
FROM STOCK_TB
FULL JOIN PRODUCT_TB USING(PRODUCT_CODE))---main 테이블
GROUP BY TEAM_CODE ,PRODUCT_CODE ,PRODUCT_NAME
ORDER BY 1,2) main
LEFT JOIN (SELECT TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME, SUM(AMOUNT) 수량
FROM STOCK_TB
FULL JOIN PRODUCT_TB USING(PRODUCT_CODE)
WHERE IN_OUT_SALES_ST = 'SALES'
GROUP BY TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME) sub ON (main.TEAM_CODE = sub.TEAM_CODE)
WHERE main.PRODUCT_CODE = sub.PRODUCT_CODE;
---------------------------------------------------------------


SELECT SUM(AMOUNT),PRODUCT_CODE,TEAM_CODE
FROM(SELECT TEAM_CODE ,PRODUCT_CODE ,PRODUCT_TB.PRODUCT_NAME PRODUCT_NAME,
(CASE 
	WHEN IN_OUT_SALES_ST = 'IN'
	THEN TO_NUMBER(TO_CHAR(AMOUNT))   
	WHEN IN_OUT_SALES_ST = 'OUT'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
	WHEN IN_OUT_SALES_ST = 'SALES'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
END) AMOUNT ,IN_OUT_SALES_ST 
FROM STOCK_TB
FULL JOIN PRODUCT_TB USING(PRODUCT_CODE)) WHERE IN_OUT_SALES_ST ='SALES'
GROUP BY TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME,IN_OUT_SALES_ST;



SELECT TEAM_CODE ,STOCK_TB.PRODUCT_CODE ,PRODUCT_TB.PRODUCT_NAME PRODUCT_NAME,
(CASE 
	WHEN IN_OUT_SALES_ST = 'IN'
	THEN TO_NUMBER(TO_CHAR(AMOUNT))   
	WHEN IN_OUT_SALES_ST = 'OUT'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
	WHEN IN_OUT_SALES_ST = 'SALES'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
END) AMOUNT 
FROM STOCK_TB
JOIN PRODUCT_TB ON(STOCK_TB.PRODUCT_CODE =PRODUCT_TB.PRODUCT_CODE);




-----------------------------------------------------------------------------------------------------
SELECT TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME,재고수량,판매수량
FROM ((SELECT TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME,재고수량,판매수량
FROM (SELECT TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME,SUM(AMOUNT) 재고수량, 0 판매수량
FROM(SELECT TEAM_CODE ,PRODUCT_CODE ,PRODUCT_TB.PRODUCT_NAME PRODUCT_NAME,
(CASE 
	WHEN IN_OUT_SALES_ST = 'IN'
	THEN TO_NUMBER(TO_CHAR(AMOUNT))   
	WHEN IN_OUT_SALES_ST = 'OUT'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
	WHEN IN_OUT_SALES_ST = 'SALES'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
END) AMOUNT
FROM STOCK_TB
FULL JOIN PRODUCT_TB USING(PRODUCT_CODE))
GROUP BY TEAM_CODE ,PRODUCT_CODE ,PRODUCT_NAME
ORDER BY 1,2 )
MINUS 
SELECT main.TEAM_CODE TEAM_CODE,main.PRODUCT_CODE PRODUCT_CODE,main.PRODUCT_NAME PRODUCT_NAME, main.수량 재고수량, 0 판매수량
FROM (SELECT TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME,SUM(AMOUNT) 수량
FROM(SELECT TEAM_CODE ,PRODUCT_CODE ,PRODUCT_TB.PRODUCT_NAME PRODUCT_NAME,
(CASE 
	WHEN IN_OUT_SALES_ST = 'IN'
	THEN TO_NUMBER(TO_CHAR(AMOUNT))   
	WHEN IN_OUT_SALES_ST = 'OUT'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
	WHEN IN_OUT_SALES_ST = 'SALES'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
END) AMOUNT 
FROM STOCK_TB
FULL JOIN PRODUCT_TB USING(PRODUCT_CODE))---main 테이블
GROUP BY TEAM_CODE ,PRODUCT_CODE ,PRODUCT_NAME
ORDER BY 1,2) main
LEFT JOIN (SELECT TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME, SUM(AMOUNT) 수량
FROM STOCK_TB
FULL JOIN PRODUCT_TB USING(PRODUCT_CODE)
WHERE IN_OUT_SALES_ST = 'SALES'
GROUP BY TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME) sub ON (main.TEAM_CODE = sub.TEAM_CODE)
WHERE main.PRODUCT_CODE = sub.PRODUCT_CODE
)
UNION
SELECT main.TEAM_CODE TEAM_CODE,main.PRODUCT_CODE PRODUCT_CODE,main.PRODUCT_NAME PRODUCT_NAME, main.수량 재고수량, sub.수량 판매수량
FROM (SELECT TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME,SUM(AMOUNT) 수량
FROM(SELECT TEAM_CODE ,PRODUCT_CODE ,PRODUCT_TB.PRODUCT_NAME PRODUCT_NAME,
(CASE 
	WHEN IN_OUT_SALES_ST = 'IN'
	THEN TO_NUMBER(TO_CHAR(AMOUNT))   
	WHEN IN_OUT_SALES_ST = 'OUT'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
	WHEN IN_OUT_SALES_ST = 'SALES'
	THEN TO_NUMBER(TO_CHAR('-'||AMOUNT))
END) AMOUNT 
FROM STOCK_TB
FULL JOIN PRODUCT_TB USING(PRODUCT_CODE))---main 테이블
GROUP BY TEAM_CODE ,PRODUCT_CODE ,PRODUCT_NAME
ORDER BY 1,2) main
LEFT JOIN (SELECT TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME, SUM(AMOUNT) 수량
FROM STOCK_TB
FULL JOIN PRODUCT_TB USING(PRODUCT_CODE)
WHERE IN_OUT_SALES_ST = 'SALES'
GROUP BY TEAM_CODE,PRODUCT_CODE,PRODUCT_NAME) sub ON (main.TEAM_CODE = sub.TEAM_CODE)
WHERE main.PRODUCT_CODE = sub.PRODUCT_CODE)
WHERE TEAM_CODE = 'DM002'
ORDER BY 2;
-------------------------------------------