--1.
SELECT STUDENT_NO 학번 , STUDENT_NAME 이름 , TO_DATE(ENTRANCE_DATE, 'RR-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 입학년도;

--SELECT STUDENT_NO 학번 , STUDENT_NAME 이름 , ENTRANCE_DATE 입학년도
--FROM TB_STUDENT
--WHERE DEPARTMENT_NO = '002';

--2.
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3.
SELECT PROFESSOR_NAME 교수이름,PROFESSOR_SSN--TRUNC(MONTHS_BETWEEN(SYSDATE , TO_DATE('19'||SUBSTR(PROFESSOR_SSN,1,6), 'YYYYMMDD'))/12) 나이--SUBSTR(PROFESSOR_SSN,1,2)--100-SUBSTR(PROFESSOR_SSN,1,2) + TO_CHAR(SYSDATE,'YY')   -- CEIL(MONTHS_BETWEEN(SYSDATE , TO_DATE(SUBSTR(PROFESSOR_SSN,1,6), 'RRMMDD'))/12) 나이
FROM TB_PROFESSOR
ORDER BY 2;

SELECT PROFESSOR_NAME 교수이름,TRUNC(MONTHS_BETWEEN(SYSDATE , TO_DATE('19'||SUBSTR(PROFESSOR_SSN,1,6), 'YYYYMMDD'))/12) 나이--SUBSTR(PROFESSOR_SSN,1,2)--100-SUBSTR(PROFESSOR_SSN,1,2) + TO_CHAR(SYSDATE,'YY')   -- CEIL(MONTHS_BETWEEN(SYSDATE , TO_DATE(SUBSTR(PROFESSOR_SSN,1,6), 'RRMMDD'))/12) 나이
FROM TB_PROFESSOR
ORDER BY 2;

--4.
SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;

--5.
SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT
WHERE (EXTRACT(YEAR FROM ENTRANCE_DATE) -('19'||SUBSTR(STUDENT_SSN ,1,2))) >19;
--WHERE TRUNC(MONTHS_BETWEEN(ENTRANCE_DATE  , TO_DATE('19'||SUBSTR(STUDENT_SSN ,1,6), 'YYYYMMDD'))/12)


--6. 2020 년 크리스마스의 요일 
SELECT TO_CHAR(TO_DATE('201225','YYMMDD'),'DAY') FROM DUAL;

--7.
SELECT TO_DATE('99/10/11','YY/MM/DD') FROM DUAL;
SELECT TO_DATE('49/10/11','YY/MM/DD') FROM DUAL;
SELECT TO_DATE('99/10/11','RR/MM/DD') FROM DUAL;
SELECT TO_DATE('49/10/11','RR/MM/DD') FROM DUAL;

--8.
SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

--9.
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10.
SELECT DEPARTMENT_NO,COUNT(*) 
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11.
SELECT COUNT(*)
FROM TB_STUDENT 
GROUP BY COACH_PROFESSOR_NO 
HAVING COACH_PROFESSOR_NO IS NULL;

--12.
SELECT SUBSTR(TERM_NO,1,4) 년도, ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4);

--13.
SELECT NVL(DEPARTMENT_NO,DEPARTMENT_NO), NVL(COUNT(*),0) --ABSENCE_YN
FROM  TB_STUDENT
GROUP BY DEPARTMENT_NO, ABSENCE_YN --IS NULL
HAVING ABSENCE_YN NOT IN ('N')
ORDER BY 1;

--14.
SELECT STUDENT_NAME ,COUNT(*) 
FROM  TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY 1;

--15.
SELECT NVL(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,1,4)) 년도, SUBSTR(TERM_NO,5,6),ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,6))
ORDER BY 1,2;


