--1.
SELECT STUDENT_NO 학번 , STUDENT_NAME 이름 , TO_DATE(ENTRANCE_DATE, 'RR-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 입학년도;

--SELECT STUDENT_NO 학번 , STUDENT_NAME 이름 , ENTRANCE_DATE 입학년도
--FROM TB_STUDENT
--WHERE DEPARTMENT_NO = '002';

--2.
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--4.
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR;