--1.
SELECT STUDENT_NO 학번 , STUDENT_NAME 이름 , TO_DATE(ENTRANCE_DATE, 'RR-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 입학년도;

--SELECT STUDENT_NO 학번 , STUDENT_NAME 이름 , ENTRANCE_DATE 입학년도
--FROM TB_STUDENT
--WHERE DEPARTMENT_NO = '002';

--2.
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3.
SELECT PROFESSOR_NAME 교수이름,PROFESSOR_SSN--TRUNC(MONTHS_BETWEEN(SYSDATE , TO_DATE('19'||SUBSTR(PROFESSOR_SSN,1,6), 'YYYYMMDD'))/12) 나이--SUBSTR(PROFESSOR_SSN,1,2)--100-SUBSTR(PROFESSOR_SSN,1,2) + TO_CHAR(SYSDATE,'YY')   -- CEIL(MONTHS_BETWEEN(SYSDATE , TO_DATE(SUBSTR(PROFESSOR_SSN,1,6), 'RRMMDD'))/12) 나이
FROM TB_PROFESSOR
ORDER BY 2;

SELECT PROFESSOR_NAME 교수이름,TRUNC(MONTHS_BETWEEN(SYSDATE , TO_DATE('19'||SUBSTR(PROFESSOR_SSN,1,6), 'YYYYMMDD'))/12) 나이--SUBSTR(PROFESSOR_SSN,1,2)--100-SUBSTR(PROFESSOR_SSN,1,2) + TO_CHAR(SYSDATE,'YY')   -- CEIL(MONTHS_BETWEEN(SYSDATE , TO_DATE(SUBSTR(PROFESSOR_SSN,1,6), 'RRMMDD'))/12) 나이
FROM TB_PROFESSOR
ORDER BY 2;

