SELECT PRICE_NO, MAIN.PRODUCT_CODE , SALES_CODE ,START_DATE ,END_DATE , SALES_PER, PRODUCT_PRICE*(1-SALES_PER), PRODUCT_PRICE
FROM PRODUCT_PRICE_TB PPT
LEFT JOIN SALES_TB USING(SALES_CODE)
LEFT JOIN PRODUCT_TB MAIN ON (MAIN.PRODUCT_CODE = PPT.PRODUCT_CODE)
LEFT JOIN STOCK_TB ST ON (MAIN.PRODUCT_CODE = ST.PRODUCT_CODE)
WHERE IN_OUT_SALES_ST = 'SALES'
AND STOCK_ST_DATE BETWEEN START_DATE AND END_DATE
ORDER BY 1 DESC, 2 DESC;





SELECT *  
FROM PRODUCT_TB;